version: "3"
services:
  api:
    container_name: open-vault-api
    restart: always
    build: .
    ports:
      - "443:8000"
    links:
      - mongo
    environment: 
      DATABASE_URL: mongodb://mongo:27017/open-vault
      URL: https://localhost
      PORT: 8000
      SESSION_SECRET: <SECRET>
      WINDOWS_INSTALLER: true
      MAC_INSTALLER: true
      LINUX_INSTALLER: true

  mongo:
    container_name: open-vault-mongo
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
