version: "3"
services:
  server:
    build: .
    image: open-vault
    restart: always
    ports:
      - "80:8080"
      - "443:4443"
    links:
      - mongo
    environment: 
      URL: https://localhost
      SESSION_SECRET: <SECRET>
      #SSL: true
      
      # Update the following variables if you built the client by yourself #
      #WINDOWS_INSTALLER: '/assets/installers/file_name.exe'
      #MAC_INSTALLER: '/assets/installers/file_name.dmg'
      #LINUX_DEB_INSTALLER: '/assets/installers/file_name.deb'
      #LINUX_RPM_INSTALLER: '/assets/installers/file_name.rpm'

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
