---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvault-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: leandrolorenzini/open-vault:latest
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: SESSION_SECRET
          value: "123"
        - name: URL
          value: "https://localhost" # This must be the URL to the proxy (the one used ny your end-users)

        # If you have built the client by yourself, set the following variables with 
        # the client installation file location. It can be an external URL or file path
        # If you use a volume, mount it under /usr/src/app/assets, eg. /usr/src/app/assets/installers
        # and then assign the following variables, eg. '/assets/installers/filename.exe'
        - name: WINDOWS_INSTALLER
          value:
        - name: MAC_INSTALLER
          value:
        - name: LINUX_DEB_INSTALLER
          value:
        - name: LINUX_DEB_INSTALLER
          value:

---
apiVersion: v1
kind: Service
metadata:
  name: openvault
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080