---
name: Build

on:
  workflow_dispatch:

jobs:

  build-react:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: cd gui && npm ci

    - name: Build react app
      run: |
        export REACT_APP_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')
        cd gui && npm run build
        zip -r build.zip build/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: react
        path: |
          gui/build.zip

  build-linux:
    needs: [ build-react ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: react
    
    - name: Unzip react build
      run: |
        mv build.zip gui/build.zip
        cd gui && unzip build.zip

    - name: Build electron app
      run: cd gui && npm ci && npm run make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: |
          gui/out/make/*

  build-macos:
    needs: [ build-react ]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: react
    
    - name: Unzip react build
      run: |
        mv build.zip gui/build.zip
        cd gui && unzip build.zip

    - name: Build electron app
      run: cd gui && npm ci && npm run make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: |
          gui/out/make/*

  build-windows:
    needs: [ build-react ]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: react
    
    - name: Unzip react build
      run: |
        mv build.zip gui/build.zip
        cd gui && unzip build.zip

    - name: Build electron app
      run: cd gui && npm ci && npm run make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: |
          gui/out/make/
